[package]
name = "io_extract"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "io_extract"
path = "src/main.rs"

[dependencies]
flate2 = "1.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true