[package]
name = "gtf2bed"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gtf2bed"
path = "src/main.rs"

[dependencies]
flate2 = "1.0"
regex = "1.10"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
