FROM ubuntu:22.04
# Update and upgrade the package list
RUN apt-get update -y && apt-get upgrade -y
# Install necessary packages including gcc and build-essential
RUN apt-get install -y wget cpanminus build-essential
# Install Data::Dumper Perl module
RUN cpanm Data::Dumper
# Download the gtf2bed script
RUN wget https://raw.githubusercontent.com/ExpressionAnalysis/ea-utils/master/clipper/gtf2bed
# Make the gtf2bed script executable
RUN chmod +x gtf2bed
# Move gtf2bed to /usr/local/bin to add it to the PATH
RUN mv gtf2bed /usr/local/bin/